version: '3.9'

services:
  db:
    container_name: db
    image: postgres:latest
    hostname: db
    restart: unless-stopped
    environment:
      POSTGRES_DB: mcontigo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: s3cr3tp4ssw0rd
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 3

  api:
    container_name: api
    image: 'kotlin-dev-challenge:latest'
    build:
      context: .
    hostname: api
    restart: unless-stopped
    environment:
      - DB_HOST=db
      - DB_NAME=mcontigo
      - DB_USER=postgres
      - DB_PASS=s3cr3tp4ssw0rd
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  database_data:
    driver: local
