spring:
  application:
    name: mcontigo-api
  profiles:
    active: ${ENVIRONMENT:development}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:mcontigo}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:s3cr3tp4ssw0rd}
  cloud:
    config:
      enabled: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        time_zone: UTC
      org:
        hibernate:
          envers:
            default_schema: public
            store_data_at_delete: true

feign:
  client:
    config:
      coindesk-api:
        logger-level: basic
        connect-timeout: 15000
        read-timeout: 15000
        follow-redirects: true

debug: false

server:
  port: 8080

clients:
  coindesk-api:
    url: ${COINDESK_URL:https://api.coindesk.com}
